global using AutoMapper;
global using FluentValidation;
global using MediatR;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Throw;